### PR TITLE
added autoLoad to option that gets passed through to soundManager

### PR DESCRIPTION
**Pull request by pswoodworth**
Pretty much does just that! Updated docs as well. thanks!

### CODE REVIEW

**Comment by pswoodworth** [comment]
hey @leoasis would love to get this merged/make changes if need be!

**Review by leoasis — APPROVED** [review]
Hey sorry for not getting back to this PR. Just took a look and it's just fine as is! Thanks for the contribution!

**Comment by pswoodworth** [comment]
Thanks @leoasis! Love the project, btw 🙏

**Comment by leoasis** [comment]
Glad you like it! Thanks again for helping improve it

**Pull request merged**
