### PR TITLE
improved readability of code

### PR DESCRIPTION
**Pull request by stmoreau**
Thank you very much for creating this library. I am using it and it has been amazing so far.

I did some work to improve a bit the readability mainly of the examples you have but of the src code a bit as well.
No functional changes at all so, it should be pretty straightforward.

Thanks in advance for accepting my PR 😄

### CODE REVIEW

**Review by peinguin — CHANGES_REQUESTED** [review]
strange codestyle

**Comment by stmoreau** [comment]
It's pretty standard I would say @peinguin

**Comment by leoasis** [comment]
Hi @stmoreau! Thanks for your PR, I've written the examples and initial code a long time ago, and now my code style is more or less similar to what you changed here. However, this is just style, and I'd rather keep the files unchanged so it's easier to follow the history of lines changed without much noise.

I think on the other side, writing the examples in this more standard style may be helpful for people looking at them, so I'd accept this PR but only for example code (not the library code nor package json or other artifacts). Let me know if that's something you'd be willing to change!

**Comment by stmoreau** [comment]
Hey @leoasis! Thank you for your fast response, I will create a new PR asap 💯

**Pull request closed without merging**
